nelmio_api_doc:
    documentation:
        info:
            title: Messenger API
            description: API for messenger-api methods and more
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
